# -------------------------
# Stage 1 : Composer
# -------------------------
FROM composer:2 AS vendor
WORKDIR /app

# Copier tout le projet pour que artisan existe
COPY . .

RUN composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction


# -------------------------
# Stage 2 : Node (build front)
# -------------------------
FROM node:18 AS node_builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build


# -------------------------
# Stage 3 : PHP-FPM final
# -------------------------
FROM php:8.2-fpm-alpine

WORKDIR /var/www/html

RUN apk add --no-cache bash git icu-dev libzip-dev zlib-dev libpng-dev oniguruma-dev \
 && docker-php-ext-install pdo_mysql mbstring zip exif intl

# Copier vendor depuis le stage composer
COPY --from=vendor /app/vendor /var/www/html/vendor

# Copier le build front
COPY --from=node_builder /app/public /var/www/html/public

# Copier le reste du projet
COPY . .

# Permissions Laravel
RUN chown -R www-data:www-data storage bootstrap/cache

EXPOSE 9000
CMD ["php-fpm"]
